<?php

return [
    'targets' => [
        'mysql' => [
            'label' => 'MySQL — learn (магазин)',
            'group' => 'Навчальні бази',
            'driver' => 'mysql',
            'analyze' => 'EXPLAIN ANALYZE ',
            'dsn' => 'mysql:host=mysql;port=3306;dbname=learn;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
        ],
        'mariadb' => [
            'label' => 'MariaDB — learn (бібліотека)',
            'group' => 'Навчальні бази',
            'driver' => 'mysql',
            'analyze' => 'ANALYZE ',
            'dsn' => 'mysql:host=mariadb;port=3306;dbname=learn;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
        ],
        'postgres' => [
            'label' => 'PostgreSQL — learn / shop (магазин)',
            'group' => 'Навчальні бази',
            'driver' => 'pgsql',
            'analyze' => 'EXPLAIN (ANALYZE, BUFFERS) ',
            'dsn' => 'pgsql:host=postgres;port=5432;dbname=learn',
            'user' => 'student',
            'password' => 'student',
            'init' => ['SET search_path TO shop'],
        ],
        'mysql_big' => [
            'label' => 'MySQL — shop_big (100000 замовлень)',
            'group' => 'Великі дані',
            'driver' => 'mysql',
            'analyze' => 'EXPLAIN ANALYZE ',
            'dsn' => 'mysql:host=mysql;port=3306;dbname=shop_big;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
        ],
        'mariadb_big' => [
            'label' => 'MariaDB — shop_big (100000 замовлень)',
            'group' => 'Великі дані',
            'driver' => 'mysql',
            'analyze' => 'ANALYZE ',
            'dsn' => 'mysql:host=mariadb;port=3306;dbname=shop_big;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
        ],
        'postgres_big' => [
            'label' => 'PostgreSQL — shop_big (100000 замовлень)',
            'group' => 'Великі дані',
            'driver' => 'pgsql',
            'analyze' => 'EXPLAIN (ANALYZE, BUFFERS) ',
            'dsn' => 'pgsql:host=postgres;port=5432;dbname=learn',
            'user' => 'student',
            'password' => 'student',
            'init' => ['SET search_path TO shop_big'],
        ],
        'sandbox_mysql' => [
            'label' => 'Пісочниця MySQL',
            'group' => 'Пісочниця',
            'driver' => 'mysql',
            'analyze' => 'EXPLAIN ANALYZE ',
            'dsn' => 'mysql:host=mysql;port=3306;dbname=sandbox;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
            'writable' => true,
        ],
        'sandbox_mariadb' => [
            'label' => 'Пісочниця MariaDB',
            'group' => 'Пісочниця',
            'driver' => 'mysql',
            'analyze' => 'ANALYZE ',
            'dsn' => 'mysql:host=mariadb;port=3306;dbname=sandbox;charset=utf8mb4',
            'user' => 'student',
            'password' => 'student',
            'writable' => true,
        ],
        'sandbox_postgres' => [
            'label' => 'Пісочниця PostgreSQL',
            'group' => 'Пісочниця',
            'driver' => 'pgsql',
            'analyze' => 'EXPLAIN (ANALYZE, BUFFERS) ',
            'dsn' => 'pgsql:host=postgres;port=5432;dbname=sandbox',
            'user' => 'student',
            'password' => 'student',
            'writable' => true,
        ],
    ],
    'mongo' => [
        'uri' => 'mongodb://root:student@mongo:27017/learn?authSource=admin',
    ],
    'redis' => [
        'host' => 'redis',
        'port' => 6379,
    ],
];
